# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"
    resolvers:
        default:
            web_path: ~

#
#    # define your filter sets under this option
    filter_sets:
        cache: ~
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        unscaled:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                scale:
                    to: 1

        unscaled_200:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 200
        unscaled_600:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 600
        unscaled_1024:
#            jpeg_quality: 85
#            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 1024
            post_processors:
                mozjpeg: { quality: 70 }
        unscaled_1920:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 1920

        # available, but I'm not using it
        size_1200:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                scale:
                    dim:          [1200, 1200]

        # available, but I'm not using it
        size_600:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                thumbnail:
                    size:          [600, 600]
                    mode:          outbound
                    allow_upscale: true

        size_200:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                thumbnail:
                    size:          [200, 200]
                    mode:          outbound
                    allow_upscale: true
#                scale:
#                    dim: [ 200, 200 ]

        size_facebook:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                thumbnail:
                    size: [ 960, 960 ]
                    mode: outbound
                    allow_upscale: true

        product_small:
            jpeg_quality:          75
            png_compression_level: 8
            filters:
                thumbnail:
                    size:          [150, 200]
                    mode:          outbound
                    allow_upscale: true

        product_medium:
            jpeg_quality:          75
            png_compression_level: 8
            filters:
                thumbnail:
#                    size:          [300, 400]
#                    size:          [400, 533]
                    size:          [510, 680]
                    mode:          outbound
                    allow_upscale: true

        product_large:
            jpeg_quality:          75
            png_compression_level: 8
            filters:
                thumbnail:
                    size:          [768, 1024]
                    mode:          outbound
                    allow_upscale: true
                watermark_image:
                    image: "/public/uploads/images/icons/watermark.png"
                    size: 0.25
                    position: bottomleft

#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'